version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./tickets.db:/app/tickets.db
      - ./.env.local:/app/.env.local
    restart: always
    environment:
      - NODE_ENV=production
