// Seed inicial para el editor de planillas de limpieza.
// Solo se inserta si la tabla `limpieza_clientes` está vacía (primer arranque).
// Cero efecto en tablas históricas (`limpieza_asistencia`, etc).

export interface SeedPuesto { nombre: string; cantidad: number; }
export interface SeedTurno { turno: string; puestos: SeedPuesto[]; }
export interface SeedSector { name: string; turnos: SeedTurno[]; }
export interface SeedCliente { name: string; sectores: SeedSector[]; }

export const PLANILLA_SEED: SeedCliente[] = [
    {
        name: 'CASMU',
        sectores: [
            {
                name: 'Asilo',
                turnos: [
                    { turno: '6 A 14', puestos: [
                        { nombre: 'ENCARGADO', cantidad: 1 },
                        { nombre: 'ASILO', cantidad: 5 },
                        { nombre: 'VIDRIERO', cantidad: 1 },
                        { nombre: 'MOVILES', cantidad: 1 },
                        { nombre: 'LOCAL 8', cantidad: 1 },
                        { nombre: 'CONTAC CENTER', cantidad: 1 },
                        { nombre: 'ALMACENES', cantidad: 1 },
                        { nombre: 'DESPENSA', cantidad: 1 },
                        { nombre: 'MEDICAMENTOS', cantidad: 1 },
                    ] },
                    { turno: '14 A 22', puestos: [
                        { nombre: 'ENCARGADO', cantidad: 1 },
                        { nombre: 'ASILO', cantidad: 4 },
                        { nombre: 'CONTAC CENTER', cantidad: 1 },
                        { nombre: 'LOCAL 8', cantidad: 1 },
                        { nombre: 'MOVILES', cantidad: 1 },
                    ] },
                ],
            },
            {
                name: 'Roperia',
                turnos: [
                    { turno: '6 A 14', puestos: [] },
                    { turno: '12 A 20', puestos: [] },
                    { turno: '15 A 23', puestos: [] },
                ],
            },
            {
                name: 'Torre 2',
                turnos: [
                    { turno: '6 A 14', puestos: [
                        { nombre: 'ENCARGADO/A', cantidad: 1 },
                        { nombre: 'URG-GINE', cantidad: 1 },
                        { nombre: 'URG-PEDIATRICA', cantidad: 1 },
                        { nombre: 'ADICIONAL SERVICIO', cantidad: 1 },
                        { nombre: '1B', cantidad: 1 },
                        { nombre: '2B', cantidad: 1 },
                        { nombre: '2C', cantidad: 1 },
                        { nombre: '3C', cantidad: 1 },
                        { nombre: '5º MATTER', cantidad: 1 },
                        { nombre: 'PLANTA', cantidad: 1 },
                        { nombre: 'ABREU', cantidad: 1 },
                        { nombre: 'C.MEDICO', cantidad: 1 },
                        { nombre: 'PEON', cantidad: 3 },
                        { nombre: 'SOE', cantidad: 1 },
                        { nombre: 'COMPACTADORA', cantidad: 1 },
                        { nombre: 'VIDRIERO', cantidad: 1 },
                    ] },
                    { turno: '14 A 22', puestos: [
                        { nombre: 'ENCARGADO/A', cantidad: 1 },
                        { nombre: 'URG-GINE', cantidad: 1 },
                        { nombre: 'URG-PEDIATRICA', cantidad: 1 },
                        { nombre: '1B', cantidad: 1 },
                        { nombre: '2B', cantidad: 1 },
                        { nombre: '2C', cantidad: 1 },
                        { nombre: '3C', cantidad: 1 },
                        { nombre: '5º MATTER', cantidad: 1 },
                        { nombre: 'ABREU', cantidad: 1 },
                        { nombre: 'PLANTA', cantidad: 1 },
                        { nombre: 'PEON', cantidad: 2 },
                        { nombre: 'SOE', cantidad: 1 },
                        { nombre: 'COMPACTADORA', cantidad: 1 },
                    ] },
                    { turno: '22 A 06', puestos: [
                        { nombre: 'ENCARGADO/A', cantidad: 1 },
                        { nombre: 'URG-GINE', cantidad: 1 },
                        { nombre: 'URG-PEDIATRICA', cantidad: 1 },
                        { nombre: '1B', cantidad: 1 },
                        { nombre: '2B', cantidad: 1 },
                        { nombre: '2C', cantidad: 1 },
                        { nombre: '3C', cantidad: 1 },
                        { nombre: '5º MATTER', cantidad: 1 },
                        { nombre: 'PEON', cantidad: 1 },
                        { nombre: 'COMPACTADORA', cantidad: 1 },
                    ] },
                ],
            },
            {
                name: 'Policlinico',
                turnos: [
                    { turno: '6 A 14', puestos: [
                        { nombre: 'ENC', cantidad: 1 },
                        { nombre: '2DO', cantidad: 1 },
                        { nombre: 'P BAJA', cantidad: 1 },
                        { nombre: 'FISIATRIA', cantidad: 1 },
                        { nombre: 'OFTA', cantidad: 1 },
                        { nombre: 'UROLOGIA', cantidad: 1 },
                        { nombre: 'LABORAT', cantidad: 1 },
                        { nombre: 'PEON', cantidad: 2 },
                        { nombre: 'VIDRIERO', cantidad: 1 },
                    ] },
                    { turno: '14 A 22', puestos: [
                        { nombre: 'ENC', cantidad: 1 },
                        { nombre: '2DO', cantidad: 1 },
                        { nombre: 'P BAJA', cantidad: 1 },
                        { nombre: 'FISIATRIA', cantidad: 1 },
                        { nombre: 'QUIRURG', cantidad: 1 },
                        { nombre: 'NEFRO', cantidad: 1 },
                        { nombre: 'OFTA', cantidad: 1 },
                        { nombre: 'LABORAT', cantidad: 1 },
                        { nombre: 'PEON', cantidad: 2 },
                    ] },
                    { turno: '22 A 06', puestos: [
                        { nombre: '1', cantidad: 1 },
                        { nombre: '2', cantidad: 1 },
                        { nombre: '3', cantidad: 1 },
                        { nombre: 'MÓVILES', cantidad: 1 },
                        { nombre: 'RETÉN', cantidad: 1 },
                    ] },
                    { turno: 'HEMOTERAPIA', puestos: [
                        { nombre: 'HEMOTERAPIA', cantidad: 2 },
                        { nombre: 'TOMOGRAFO', cantidad: 2 },
                        { nombre: 'ENDOSCOPIA', cantidad: 2 },
                        { nombre: 'QUIRURGICA', cantidad: 1 },
                        { nombre: 'PISCINA', cantidad: 2 },
                        { nombre: 'ECONOMATO 1727', cantidad: 1 },
                        { nombre: 'C. DE MAMAS', cantidad: 3 },
                        { nombre: 'COMPACTADORA', cantidad: 1 },
                    ] },
                ],
            },
            {
                name: 'Pisos Vip',
                turnos: [
                    { turno: '6 A 14', puestos: [
                        { nombre: 'ENC-6 A 14', cantidad: 1 },
                        { nombre: 'AUXILIAR 6º', cantidad: 2 },
                        { nombre: 'LIMPIADORA 6º', cantidad: 1 },
                        { nombre: 'AUXILIAR 5º', cantidad: 1 },
                        { nombre: 'LIMPIADORA 5º', cantidad: 1 },
                        { nombre: 'AUXILIAR 4º', cantidad: 1 },
                        { nombre: 'LIMPIADORA 4º', cantidad: 1 },
                    ] },
                    { turno: '14 A 22', puestos: [
                        { nombre: 'ENC-14 A 22', cantidad: 1 },
                        { nombre: 'AUXILIAR 6º', cantidad: 2 },
                        { nombre: 'LIMPIADORA 6º', cantidad: 1 },
                        { nombre: 'AUXILIAR 5º', cantidad: 1 },
                        { nombre: 'LIMPIADORA 5º', cantidad: 1 },
                        { nombre: 'AUXILIAR 4º', cantidad: 1 },
                        { nombre: 'LIMPIADORA 4º', cantidad: 1 },
                    ] },
                    { turno: '22 A 06', puestos: [
                        { nombre: 'ENC-22 A 06', cantidad: 1 },
                        { nombre: 'LIMPIADORA 6º', cantidad: 1 },
                        { nombre: 'AUXILIAR 5º', cantidad: 1 },
                        { nombre: 'AUXILIAR 4º', cantidad: 1 },
                    ] },
                ],
            },
            {
                name: 'Torre 1',
                turnos: [
                    { turno: '6 A 14', puestos: [
                        { nombre: 'ENCARGADO/A', cantidad: 1 },
                        { nombre: 'URGENCIA', cantidad: 4 },
                        { nombre: 'URGENCIA 7 A 15', cantidad: 1 },
                        { nombre: 'AUXILIAR', cantidad: 2 },
                        { nombre: '3º AUXILIAR', cantidad: 2 },
                        { nombre: '2D', cantidad: 2 },
                        { nombre: '1D', cantidad: 2 },
                        { nombre: 'PEON', cantidad: 2 },
                        { nombre: 'VIDRIERO', cantidad: 1 },
                    ] },
                    { turno: '14 A 22', puestos: [
                        { nombre: 'ENCARGADO/A', cantidad: 1 },
                        { nombre: 'URGENCIA', cantidad: 4 },
                        { nombre: 'URGENCIA 14 A 18', cantidad: 1 },
                        { nombre: 'URGENCIA 18 A 22', cantidad: 1 },
                        { nombre: 'AUXILIAR', cantidad: 2 },
                        { nombre: '3º AUXILIAR', cantidad: 2 },
                        { nombre: '2D', cantidad: 2 },
                        { nombre: '1D', cantidad: 2 },
                        { nombre: 'PEON', cantidad: 2 },
                    ] },
                    { turno: '22 A 06', puestos: [
                        { nombre: 'ENCARGADO/A', cantidad: 1 },
                        { nombre: 'URGENCIA', cantidad: 4 },
                        { nombre: 'AUXILIAR', cantidad: 1 },
                        { nombre: 'AUXILIAR AISLAMIENTO', cantidad: 1 },
                        { nombre: '3º AUXILIAR', cantidad: 1 },
                        { nombre: '2D', cantidad: 1 },
                        { nombre: '1D', cantidad: 1 },
                        { nombre: 'PEON', cantidad: 1 },
                    ] },
                ],
            },
            {
                name: 'Seguridad',
                turnos: [
                    { turno: '6 A 14', puestos: [] },
                    { turno: '14 A 22', puestos: [] },
                    { turno: '22 A 06', puestos: [
                        { nombre: 'Encargado', cantidad: 1 },
                        { nombre: 'Cabina Urgencia', cantidad: 1 },
                        { nombre: 'Recorrida (Medisgroup)', cantidad: 1 },
                        { nombre: 'Cabina Abreu', cantidad: 1 },
                        { nombre: 'Sede Administrativa', cantidad: 1 },
                        { nombre: 'Tesorería', cantidad: 1 },
                        { nombre: 'Visita CTI', cantidad: 1 },
                        { nombre: 'Portería Torre 1', cantidad: 1 },
                        { nombre: 'Portería Torre 2', cantidad: 1 },
                        { nombre: 'Local 8', cantidad: 1 },
                        { nombre: 'Policlínico (puerta 8)', cantidad: 1 },
                        { nombre: 'Salud Mental', cantidad: 1 },
                        { nombre: 'Alarma Asilo', cantidad: 1 },
                        { nombre: 'Cocina', cantidad: 1 },
                    ] },
                ],
            },
        ],
    },
];
