/** Lista de artículos para los formularios de solicitud de materiales en logística */
export const ARTICULOS_MATERIALES: string[] = [
  "Acople  De Riego",
  "Acople de Manguera",
  "Acople Manguera-Manguera 1/2\"",
  "Acople para Canilla",
  "Adaptador Cudy Wifi Ac 1300",
  "Adaptador vga hdmi",
  "Alargue 15 Mts (Contacto Electricidad)",
  "Alargue 20 Mts (Contacto-Electricida)",
  "Alargue 30 Mts (Contacto Electricidad)",
  "Alcohol al 70% (fadowel)",
  "Alcohol Isopropílico (Sansei)",
  "Amonio Cuaternario DS919 (IPL)",
  "ANTIPARRA AVIATOR TRANSPARENTE",
  "Arnes 4 Puntas Cuerpo Completo",
  "Arnes Milenium Standard Plastico",
  "ARNES SINGER SUSPENSION 5P",
  "Aromatizador Glade Fragancia Lavanda y Vainilla Aerosol (Aldo)",
  "Aromatizador Glade Fragancia Limón Aerosol (Aldo)",
  "Aspiradora 15Lts Ecolux AS15",
  "Aspiradora 30Lts Ecolux AS30",
  "Aspiradora De Mano Punktal Pk-410",
  "Aspiradora enxuta Negra C/Bolsa",
  "ASPIRADORA MONTANA - 15 LTS",
  "Balde Amarillo 4lts (Bettasul)",
  "Balde Azul 4lts (Bettasul)",
  "Balde Grande Azul (JDS)",
  "Balde Grande Rojo (JDS)",
  "Balde Grande Verde (JDS)",
  "Bandas Elasticas Paquete 200g",
  "BARRA ADHESIVA F.CASTELL 8122-22GRS.",
  "Bibliorato Omega A4 Negro",
  "Bicrosol-D",
  "Block Stick 50x50mm",
  "Block Stick 51x38mm",
  "Block Stick 76x76mm",
  "bolígrafo BIC Azul (Aldo)",
  "Boligrafo BIC (ALDO)",
  "Boligrafo bic cristal dura+color azul 1.0 mm caja x 50",
  "Bolsa Celeste 1x1",
  "Bolsa de Aspiradora",
  "Bolsa Negra 1x1",
  "Bolsa negra 50x55",
  "Bolsa Negra 70x1",
  "Bolsa para Carro Porta elementos (IPL)",
  "Bolsa Roja 120x250 (Sansei)",
  "Bolsa Roja 1x1",
  "Bolsa Roja 50X60",
  "Bolsa Roja 60x90",
  "Bolsa Roja 70x1",
  "Bolsa Transparente 1x1",
  "Bolsa Transparente 50x55",
  "Bolsa Transparente 70x1",
  "BOQUILLA 36 MM P/ASPIRADORA",
  "Borrador para pizarra Plus Office",
  "Botella de 1 Litro C/Tapa",
  "Botella de 1/2 Lt C/Tapa",
  "Botella PE-500cc",
  "Broche para engrampadora Plus Office N.10 Caja 1000",
  "Broches 26/6 x 100",
  "Broches Rapid 26/6 x 5000",
  "Cabo de Aluminio 1.60 cm",
  "Cabo de Aluminio 1.80 CM",
  "Cabo de Aluminio Extensible 3x3 Mts",
  "Caja de carton corrugado marron",
  "Candado 40cm",
  "Candado de Bronce de 30 mm (JDS)",
  "Carpeta A4 - Divisiones azules",
  "Carpeta Bibliorato C/Elastico 3Cm Verde",
  "CARPETA CON 12 DIVISIONES US-4304 NEGRA",
  "Carpeta de Plástico corrugado con Elastico Color Rojo Lomo 5 cm (Aldo)",
  "Carpeta de Plástico Corrugado con Elástico Lomo de 5 cmVerde (Aldo)",
  "Carpeta de Plástico Corrugado Negro (Aldo)",
  "Carpeta tapa transparente con broche plástico Plus Office color blanco A4",
  "Carrito Montacargas Plegable",
  "Carro Plegable 300 KG",
  "Carro Porta elemento de Limpieza Gris",
  "Carro Porta elementos de limpieza Negro",
  "Cartel Piso Mojado",
  "Casco Amarillo de seguridad",
  "CASCO ANDES TEXTIL CREMALLERA",
  "Casco Verde",
  "Celulosa - (Paño Plus Recortes)",
  "Cepillo Barrendero Fibra Dura 60cm",
  "Cepillo de Alfrombras Multifuncional CB130",
  "Cepillo de arrastré 16 plg",
  "Cepillo de lavar BLANDO HY130p",
  "Cepillo de Mano (Cameril)",
  "Cepillo de mano tipo plancha (JDS)",
  "Cepillo de Pisos de Rotativa DURO CB130",
  "Cepillo de Vidriero (JDS)",
  "Cepillo Para Discos 13\" P/Rotativa HY-130",
  "CEPILLO REDONDO 36 MM",
  "Cera al agua acrílica (Limpol)",
  "Cera Negra",
  "Cera Roble Oscuro",
  "CESTO 50 LTS BOCA DE SAPO MARRON",
  "Chaleco Reflector",
  "Cinta Adhesiva 45mm x 100m",
  "Cinta adhesiva doble faz Plus Office 19mm x 10m",
  "Cinta Adhesiva Plus Office 12 mm x 33 m",
  "Cinta de empaque Plus Office color transparente 24 mm x 50 m",
  "Cinta de empaque Plus Office color transparente 48mm x 40 m Paquete x 6 rollos",
  "Cinta Ducto 9m x 48 m negra (ALDO)",
  "Cinta eléctrica de vinilo Temflex 1700",
  "Cinta Marron 48x45mm",
  "Cinta Marron 48x90mm",
  "Cinta Para Rotuladora Brother Blanco 12mm x 8 mm",
  "Cinta Reflectiva",
  "Cinta Transparente 12x45mm",
  "Cinta Trsnparente 24mmx45m",
  "Clip gigante Plus Office redondo 50 mm Caja x 100",
  "Clip mediano Plus Office redondo 28 mm Caja x 100",
  "Clip Mediano Redondo 33 mm x 100 (Aldo)",
  "Clip Redondo 28x100mm",
  "Cloro Orgánico Klorsept",
  "Cofias Descartables",
  "Corrector de Lapicera",
  "Cuaderno 48 H Rayado",
  "Cuaderno Campus tapa flexible liso engrampado 96 hojas",
  "Cuaderno Campus tapa flexible rayado con espiral 96 hojas",
  "Cuaderno maped rayado 96 H",
  "Cuaderno papiros tapas surtidas flexible rayado 96 hojas",
  "Cuaderno Rayado 96H (Aldo)",
  "Cuadernola",
  "Cuadernola A4 Rayada",
  "Cuadernola campus university tapa flexible rayada con espiral 80 hojas 60grs",
  "Cuadernola Rayada 80H (Aldo)",
  "Cuadernola Tapa Dura 96 hojas",
  "Cubierta 50 Micantirreflejo A4",
  "Cuerda 35 mts",
  "Cuerda de 4 mm",
  "Cuerda de Vida de 14mm  y 10 Mts",
  "CUERDA NYLON CROFIL",
  "CUERDA TRENZADA 8MMX200 METROS LH-4016",
  "Delantal de PVC Blanco",
  "DESCENSOR ANTI PANICO DESCORD",
  "Desengrasante Pino amarillo",
  "Desodorante Concentrado BLUE",
  "Desodorante R. Oceanic",
  "Detergente Neutro",
  "Detergente Neutro (PROQUIM)",
  "Difusor análogo para spray aromatizador",
  "Disco de arrastre multifuncional CB130",
  "Disco de Arrastre P/Multifuncional CB130",
  "Disco Limpiador Profundo Rojo 13",
  "Disco Limpiador Profundo Rojo 19",
  "Disco Limpiador Profundo Verde 13",
  "Disco Limpiador Profundo verde 16\"",
  "Disco Limpiador Profundo Verde 19",
  "Disco lustrador Blanco 13",
  "Disco Lustrador Blanco 16\"",
  "Disco Lustrador Blanco 19",
  "Disco removedor Negro 13",
  "Disco Removedor Negro 19",
  "DISCO RESTAURADOR ROJO 51CM",
  "Embellecedor de Piso Flotante y Plastificado",
  "Embudo",
  "Enganche para Pistola o Canilla",
  "Engrampadora master 24/26",
  "Engrampadora tipo pinza hasta 20 hojas Novus B36F color negro",
  "ENGRAPADORA VERDE HC271",
  "Escalera Aluminio 4 Escalones",
  "Escalera Aluminio 5 escalones",
  "Escalera Amarilla 24 escalones",
  "Escalera Gris 7 escalones",
  "Escoba con cabo",
  "Escoba doble Barrido con cabo Dalcin (Prolimpio)",
  "Escoba Original Novica (Prolimpio-Eurobrech)",
  "Escobillón",
  "Espatula de Acero 6 cm (JDS)",
  "Esponja Amarilla y Verde",
  "Esponja Blanca (JDS) por unidad",
  "Esponja Verde 10cm (JDS) por unidad",
  "Esponja Verde 23cm Zocalera (JDS) Unidad",
  "Esponja Verde 7.5 Cm X 10 Mt",
  "Etiquetas Adhesivas P/Botellas y Baldes",
  "Etiquetas GSS Facility Services",
  "Extensible (3Mts)",
  "Extensible (6MTS)",
  "Extensible (Cameril) 4.5 mts",
  "Extensor de Aluminio 2x1.5",
  "Extensor de Aluminio 3x2",
  "FAJA LUMBAR MAZOLA L (Orvent)",
  "FAJA LUMBAR MAZOLA M (Orvent)",
  "Faja Lumbar Mazola XL (Orvent)",
  "Faja Power T - L",
  "Fibra Blanca 15 Cm X 10 Mt",
  "Fibra Verde 15 Cm X 10 Mt",
  "Ficha Hembra",
  "Film Strech 50 CMS 500 Metros",
  "Fotocontrol 220V",
  "Franela Naranja 34X34 (Cotton Trade)",
  "Frasco De Orina Esteril",
  "Fundas protectoras plus Office color transparentes A4 50 micras Paquete x100",
  "Gatillo Pulverizador",
  "Goma Autoadhesiva Plus Office Colores fuertes 5x4 cm Paq x 12 de 100 hojas (Aldo",
  "Goma de Borrar",
  "Goma de Borrar Plástica Plus Office Grande US-20 (Aldo)",
  "Goma para Lampazo Vidriero (IPL)",
  "Grafo 0.5 mm",
  "Guante Bicolor 2da Seleccion Talle 10",
  "Guante Bicolor 2da Seleccion Talle 8",
  "Guante Bicolor 2da Seleccion Talle 8.5",
  "Guante Bicolor 2da Seleccion Talle 9",
  "Guante Bicolor 2da Seleccion Talle 9.5",
  "Guante de Trabajo (Orvent)",
  "GUANTE NITRILO P SOLVENTES",
  "Guante Palma Goma Forte",
  "Guante PVC con Manga",
  "Guante Rojo Sintalc Nº 9.5",
  "Guante Rojo Sintalc Nº8",
  "Guante Rojo Sintalc Nº8.5",
  "Guante Rojo Sintalc Nº9",
  "Guantes de Trabajo (Orvent)",
  "Guantes Latex",
  "HIDROLAVADORA",
  "Hipoclorito al 100% (fadowel)",
  "Jabon Liquido para Mano Sensus 2LT",
  "Jabonero",
  "Jabonero Vidriero",
  "Jarra Medidora 1Lt (JDS)",
  "Kit de Pistola y manguera 7.5 M",
  "Lampazo doble goma 45cm con cabo extensible",
  "Lampazo Dual 35cm",
  "Lampazo Vidriero 25 cm (Cameril)",
  "Lampazo Vidriero 25 cm (IPL)",
  "Lampazo Vidriero 35cm (IPL)",
  "Lapicera Azul",
  "Lapicera Gel",
  "Lapiz de grafito 0.5",
  "LAPIZ FABER 1205ME/14 MAX CAJA 14UN",
  "Lavafregadora - Log L-1 (celeste) - Ecolux",
  "Lavafregadora - Log L-2 (Spartan gris) - Gaomei",
  "Lcd portable 15.6\\\"",
  "Lector de Codigo de Barras Netum NT-M8 2D Inalambrico",
  "Lentes de Trabajo Transparente",
  "Lentes Negras De Seguridad",
  "Limpiador Cremosos 250 ML (JDS)",
  "Limpiador Peroxido (IPL)",
  "Linea de vida soga 12x100m m55",
  "Lustrametal en Pomo",
  "Lustramuebles Aerosol",
  "Lustramuebles en Crema",
  "Manguera 32MM P/Aspiradora",
  "Manguera blanco y negro de 1/2\"",
  "Manguera C/malla 50Mts( JDS)",
  "Manguera de Riego",
  "Manguera P/Hidrolavadora",
  "Manguera Reforzada de 50 Mts",
  "Marcador de Pizarra Azul",
  "Marcador de Pizarra Negro",
  "Marcador de Pizarra Rojo",
  "Marcador de Pizarra Verde",
  "Marcador Fibra Point - Verde",
  "Marcador Fluorecente ALDO",
  "Marcador Omega Doble Punta",
  "Marcador Paint 1mm Blanco",
  "Marcador Permanente Negro",
  "Marcador Permanente Negro Faver Winner (Aldo)",
  "Marcador permanente Plus Office Marker color negro 1.3 mm",
  "Marcador permanente Plus Office punta fina color Blanco",
  "Marcador Permanete BIC color Negro (Aldo)",
  "Marcador Recargable Negro",
  "Marcadores de pizarra Plus Office 230 Estuche x 4 colores",
  "Microfibra Amarilla 32x32 (Cotton Trade)",
  "Microfibra Azul 32x32  (Cotton Trade)",
  "Microfibra Roja 32x32 (Cotton Trade)",
  "Microfibra Verde 32x32 (Cotton Trade)",
  "MOSQUETON ACERO ROSCA",
  "Notas adhesivas Plus Office flúo 7.5 x 7.5 cm 300 hojas",
  "Notas Adhesivas Post It 51x51",
  "Notas Autoadhesivas Plus Office 300 hojas 7.5x7.5 cm (Aldo)",
  "Notebook Acer Ryzen 7 16Gb 512Gb 15.6\\\"",
  "Notebook Asus Vivobook i3 8gb 256gb",
  "Organizador Met. Vertical 3 Bandejas - Verde",
  "Paño de Piso Algodon 60x50 (Cotton Trade)",
  "Paño de Piso de Microfibra Azul 55x50 (Cotton Trade)",
  "Paño de Piso de Microfibra Roja 55x50 (Cotton Trade)",
  "Paño de Piso de Microfibra Verde 55x50 (Cotton Trade)",
  "Pala con Cabo",
  "Pala Plástico Caja Negra C/Tapa",
  "PALA TRAMONTINA",
  "Palos de Fierro",
  "Papel en Resma Fanacopy 500H (Aldo)",
  "Papel Especial A4 160 grs Pack 250 hojas (Aldo)",
  "Papel Fotocopia A4",
  "Papel Higenico Elite Jumbo 500MTS",
  "Papel higiénico en rollo Elite Professional IP374 hoja simple Funda x 4 rollos",
  "Papel Resma Fanacopy color blanco A4 75 grs Paquete x 500 hojas",
  "Papelera Metalica Neox",
  "Perfume p/ Vaporizar Verbena (Limpol)",
  "Pistola Hidrolavadora Goldex",
  "PLACA DE FIJACION PINZA LAVADORA  GAOMEI GM-50 (Repuesto)",
  "Plumero sintetico Encastrable",
  "Porta Cinta 605 (Aldo)",
  "Porta Pad 13\"",
  "Porta Pad Super Kliner",
  "Portaclips Imantado Foska",
  "Precintos 2.8x200 mm",
  "Precintos 3.6 300MM",
  "PROT. AUDITIVO ALTERNATIVO 22",
  "Puntero de riego (JDS)",
  "Quitasarro Ecobat (IPL)",
  "Quitasarro Ecobat Verde (IPL)",
  "Recibos Comerciales",
  "Rejilla de Algodon",
  "Removedor de óxido Metox (sebamel)",
  "REMOVEDOR DE CERA PARA MADERA 950mL",
  "Repuesto de Mopa Plana de algodón 60x15",
  "Repuesto de Mopa Verde de Velcro 60x15",
  "Repuesto Paño de Mopa Acrílico  60x15",
  "Resaltador Amarillo",
  "Resaltador Azul",
  "Resaltador Naranja",
  "Resaltador Verde",
  "Resma A4",
  "Rotativa - Log R1 Rotativa Roja - CB130",
  "Rotativa Ecolux 13\" HY130",
  "Router Cudy Wifi Ac1200",
  "Saca Ganchos",
  "SALVACAIDAS C CABOS DE 25 CM",
  "Set 4 Baldes 4lts (Rojo,Amarillo,Azul y Verde)",
  "SILLETA PARA PINTOR",
  "Sobre Blanco 1/2 Oficio",
  "Sobre Blanco 22.9x32.4",
  "Sobre Comercial (Carta)",
  "Sobre Manila Oficio",
  "SOBRE NEOX COM. BCO.11 4X23CMS.PTE.10UNI",
  "Sobre Oficio Blanco (Aldo)",
  "Sobre Revista Blanco (Aldo)",
  "Sobre Revista Manila A4",
  "Sobres Blanco A3",
  "Soplador BG 50",
  "SOPORTE ARTICULADO PARA FIBRA SIN CABO",
  "Soporte tablet Chuwi",
  "TABLA BAMBOO C/APRIET.Y  BOLIG. SB38004",
  "Tablet Chuwi Hipad 11 Lte 6+128",
  "Talonario de Recibos 9.3 x 56 cm (Aldo)",
  "Tapaboca KN 95",
  "Tapaboca Plisado",
  "Túnica Impermeable",
  "Thinner",
  "Tijera de Acero inoxidable Plus office color azul 21,5 cm",
  "Tijera Maped",
  "Tijera Neox",
  "TIJERA NEOX 42173 21CMS.",
  "Toalla de papel intercalada Elite Professional IP325 hoja simple Caja x 15 paque",
  "Toalla Elite Interfoliada 20x19 Cm",
  "Toner TL425x + unidad imagen DL425x",
  "Trincheta Vidriero (Cameril)",
  "Tunica  Descartable",
  "Tunica Blanca Talle 42",
  "Unger Goma de Repuestos 1.05 Cms",
  "Uruguay fisico y Politico 130*95",
  "Voligoma Pomo 30 ml (Aldo)",
  "Zocalera"
];

/** Normaliza texto para búsqueda (minúsculas, sin marcas diacríticas). */
export function normalizeArticuloSearch(s: string): string {
  return s.normalize('NFD').replace(/\p{M}/gu, '').toLowerCase();
}

const MAX_ARTICULOS_SIN_BUSQUEDA = 60;
const MAX_ARTICULOS_CON_BUSQUEDA = 120;

/** Filtra la lista por texto; sin query muestra un subconjunto inicial para no saturar el DOM. */
export function filterArticulosPorBusqueda(candidates: string[], query: string): string[] {
  const q = query.trim();
  if (!q) return candidates.slice(0, MAX_ARTICULOS_SIN_BUSQUEDA);
  const nq = normalizeArticuloSearch(q);
  return candidates.filter((a) => normalizeArticuloSearch(a).includes(nq)).slice(0, MAX_ARTICULOS_CON_BUSQUEDA);
}
